config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
import debug_toolbar
from newbook.models import Hotel

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('<str:pk>/reserve/', include('newbook.urls_reserve')),
    path('<str:pk>/hotel/', include('newbook.urls_hotel')),
    path('__debug__/', include(debug_toolbar.urls))
)

newbook/models/DayCharge.py
import uuid
from django.db import models
from django.utils import timezone
from newbook.models import Hotel
from django.core.validators import MaxValueValidator, MinValueValidator


class DayCharge(models.Model):

    class Meta:
        db_table = 'dayCharge'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    hotel_id = models.ForeignKey('Hotel', on_delete=models.CASCADE)
    plan_id = models.CharField(max_length=10)
    date = models.DateField(blank=True, null=True)
    rank = models.CharField(max_length=3)
    person_num = models.IntegerField(default=0, validators=[MaxValueValidator(6)])
    charge = models.IntegerField(default=0)

    def __int__(self):
        return self.person_num

newbook/models/Hotel.py
import uuid
from django.db import models
from django.utils import timezone

class Hotel(models.Model):

  class Meta:
    db_table = 'hotel'

  id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
  hotel_id = models.CharField(primary_key=True, max_length=10, unique=True)
  hotel_name_ja = models.CharField(max_length=255)
  hotel_name_en = models.CharField(max_length=255, null=True, blank=True)

  def __str__(self):
    return self.hotel_id

newbook/models/Plan.py
import uuid
from django.db import models
from django.utils import timezone
from newbook.models import Hotel, Room


class Plan(models.Model):

    class Meta:
        db_table = 'plan'
        unique_together = (('hotel_id', 'plan_id'))

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    hotel_id = models.ForeignKey('Hotel', on_delete=models.CASCADE)
    plan_id = models.CharField(max_length=10)
    plan_name = models.CharField(max_length=10)

    def __str__(self):
        return self.plan_id

newbook/models/Room.py
import uuid
from django.db import models
from django.utils import timezone
from newbook.models import Hotel, Plan

class Room(models.Model):

    class Meta:
        db_table = 'room'
        unique_together = (('hotel_id', 'room_id'))

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    hotel_id = models.ForeignKey('Hotel', on_delete=models.CASCADE)
    room_id = models.CharField(max_length=10)
    room_name = models.CharField(max_length=10)

    def __str__(self):
        return self.room_name

newbook/models/RoomStock.py
import uuid
from django.db import models
from django.utils import timezone
from newbook.models import Hotel, Room
from django.core.validators import MaxValueValidator, MinValueValidator


class RoomStock(models.Model):

    class Meta:
        db_table = 'roomStock'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    hotel_id = models.ForeignKey('Hotel', on_delete=models.CASCADE)
    room_id = models.CharField(max_length=10)
    date = models.DateField(blank=True, null=True)
    qty = models.IntegerField(default=0, validators=[MaxValueValidator(1000)])
    reserved_out = models.IntegerField(default=0, validators=[MaxValueValidator(1000)])

    def __int__(self):
        return self.qty

newbook/forms/HotelForms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ObjectDoesNotExist
from newbook.models import Hotel, Plan, Room, RoomStock


class CreatePlan(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ('plan_id', 'plan_name')

    def __init__(self, *args, **kwargs):
        super(CreatePlan, self).__init__(*args, **kwargs)
        self.fields['plan_id'].widget.attrs = {'placeholder': 'plan_id'}
        self.fields['plan_id'].required = True
        self.fields['plan_name'].widget.attrs = {'placeholder': 'plan_name'}
        self.fields['plan_name'].required = True

    def clean_plan_id(self):
        value = self.cleaned_data['plan_id']
        return value

    def clean_plan_name(self):
        value = self.cleaned_data['plan_name']
        return value

api/views.py
from django.shortcuts import render

# Create your views here.

batch/views.py
from django.shortcuts import render

# Create your views here.

mainte/views.py
from django.shortcuts import render

# Create your views here.

templates/hotel/base.html
{% load i18n %}
{% load render_bundle from webpack_loader %}

<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">

  <title>Newbook test</title>
</head>

<body>
  <div id="app">
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js"></script>

    {% verbatim %}
    <script>
      new Vue({ el: '#app' })
    </script>
    {% endverbatim %}

  </div>
</body>

</body>

</html>

templates/hotel/planCreate.html
{% extends 'hotel/base.html' %}
{% load i18n %}
{% block content %}

■部屋
{% for room in rooms %}
<div class="post">
  <div class="date">
    <p>部屋名: {{ room.room_name }}</p>
  </div>
</div>
{% endfor %}
<br><br>


<v-app>
  <v-content>
    <v-container>Hello world</v-container>
  </v-content>

  <v-content>

    <p>{% trans 'これはテンプレートの翻訳です' %}</p>
    <p>{{ view_trans }}</p>


    <div class="sample">{{ message }}</div>
    <br>

    ■部屋
    {% for room in rooms %}
    <div class="post">
      <div class="date">
        <p>部屋名: {{ room.room_name }}</p>
      </div>
    </div>
    {% endfor %}
    <br><br>


    ■同じ条件で表示されるか
    {% for hotel in hotels %}
    <div class="post">
      <div class="date">
        <p>ホテル名: {{ hotel.hotel_name_ja }}</p>
        <p>ホテル名英語: {{ hotel.hotel_name_en }}</p>

        {% for roomstock in hotel.roomstock_set.all %}

        <p>日付: {{ roomstock.date }}</p>

        <p>部屋ID: {{ roomstock.room_id }}</p>

        <p>在庫: {{ roomstock.qty }}</p>

        <p>予約数: {{ roomstock.reserved_out }}</p>

        {% for daycharge in hotel.daycharge_set.all %}

        <p>プランID: {{ daycharge.plan_id }}</p>

        <p>料金ランク: {{ daycharge.rank }}</p>

        <p>人数: {{ daycharge.person_num }}</p>

        <p>金額: {{ daycharge.charge }}</p>

        {% endfor %}

        {% endfor %}

      </div>
    </div>
    {% endfor %}
    <br><br>

  </v-content>

  <v-container grid-list-md text-xs-center>
    <v-layout row wrap>
      <v-flex xs12>
        <v-card dark color="primary">
          <v-card-text class="px-0">12</v-card-text>
        </v-card>
      </v-flex>
      <v-flex v-for="i in 2" :key="`6${i}`" xs6>
        <v-card dark color="secondary">
          <v-card-text class="px-0">6</v-card-text>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>

</v-app>

{% endblock %}

templates/hotel/testpage.html
{% extends 'hotel/base.html' %}
{% load i18n %}
{% block content %}

■部屋
{% for room in rooms %}
<div class="post">
  <div class="date">
    <p>部屋名: {{ room.room_name }}</p>
  </div>
</div>
{% endfor %}
<br><br>


<v-app>
  <v-content>
    <v-container>Hello world</v-container>
  </v-content>

  <v-content>

    <p>{% trans 'これはテンプレートの翻訳です' %}</p>
    <p>{{ view_trans }}</p>


    <div class="sample">{{ message }}</div>
    <br>

    ■部屋
    {% for room in rooms %}
    <div class="post">
      <div class="date">
        <p>部屋名: {{ room.room_name }}</p>
      </div>
    </div>
    {% endfor %}
    <br><br>


    ■同じ条件で表示されるか
    {% for hotel in hotels %}
    <div class="post">
      <div class="date">
        <p>ホテル名: {{ hotel.hotel_name_ja }}</p>
        <p>ホテル名英語: {{ hotel.hotel_name_en }}</p>

        {% for roomstock in hotel.roomstock_set.all %}

        <p>日付: {{ roomstock.date }}</p>

        <p>部屋ID: {{ roomstock.room_id }}</p>

        <p>在庫: {{ roomstock.qty }}</p>

        <p>予約数: {{ roomstock.reserved_out }}</p>

        {% for daycharge in hotel.daycharge_set.all %}

        <p>プランID: {{ daycharge.plan_id }}</p>

        <p>料金ランク: {{ daycharge.rank }}</p>

        <p>人数: {{ daycharge.person_num }}</p>

        <p>金額: {{ daycharge.charge }}</p>

        {% endfor %}

        {% endfor %}

      </div>
    </div>
    {% endfor %}
    <br><br>

  </v-content>

  <v-container grid-list-md text-xs-center>
    <v-layout row wrap>
      <v-flex xs12>
        <v-card dark color="primary">
          <v-card-text class="px-0">12</v-card-text>
        </v-card>
      </v-flex>
      <v-flex v-for="i in 2" :key="`6${i}`" xs6>
        <v-card dark color="secondary">
          <v-card-text class="px-0">6</v-card-text>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>

</v-app>

{% endblock %}

templates/mypage/login.html
{% load i18n %}
<html>

<head></head>

<body>

  ログイン画面


  <p>{% trans 'これはテンプレートの翻訳です' %}</p>
  <p>{{ view_trans }}</p>
  あああ

  <h2 class="subtitle">
    Nuxt.js project
    <p>{% trans 'これはテンプレートの翻訳です' %}</p>
    <p></p>
  </h2>
  <div class="links"><a href="https://nuxtjs.org/" target="_blank" class="button--green">Documentation</a> <a href="https://github.com/nuxt/nuxt.js"
      target="_blank" class="button--grey">GitHub</a></div>
  </div>
  </section>

</body>

</html>

templates/reserve/testpage.html
{% load i18n %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>

<head>
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>

<body>
予約画面





  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js"></script>

  {% verbatim %}
  <script>
    new Vue({ el: '#app' })
  </script>
  {% endverbatim %}

</body>


</html>